# Generated by Django 5.2.15 on 2026-07-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='generated_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='insights',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='summary_data',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_budget',
        ),
        migrations.RemoveField(
            model_name='report',
            name='total_spent',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
    ]
