# Generated by Django 5.2.15 on 2026-07-03 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('housing', 'Housing/Rent'), ('groceries', 'Groceries'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('insurance', 'Insurance/Healthcare'), ('other', 'Other')], default='other', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
