# Generated by Django 5.2.15 on 2026-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_options_budget_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-created_at'], 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='limit_amount',
            new_name='budget_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('travel', 'Travel'), ('shopping', 'Shopping'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('bills', 'Bills'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=50),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
