# Generated by Django 5.2.15 on 2026-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_alter_budget_options_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
