# Generated by Django 5.2.15 on 2026-08-07 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_budget_budget_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('AED', 'UAE Dirham (AED)'), ('JPY', 'Japanese Yen (JPY)')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
