# Generated by Django 5.2.15 on 2026-07-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
