# Generated by Django 5.2.15 on 2026-07-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_options_expense_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
