# Generated by Django 5.2.15 on 2026-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('housing', 'Housing/Rent'), ('food', 'Food'), ('groceries', 'Groceries'), ('utilities', 'Utilities'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('insurance', 'Insurance/Healthcare'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
