# Generated by Django 5.2.15 on 2026-08-07 06:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_alter_budget_budget_amount'),
        ('expenses', '0006_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budgets.budget'),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (INR)'), ('USD', 'US Dollar (USD)'), ('EUR', 'Euro (EUR)'), ('GBP', 'British Pound (GBP)'), ('JPY', 'Japanese Yen (JPY)'), ('CAD', 'Canadian Dollar (CAD)'), ('AUD', 'Australian Dollar (AUD)'), ('SGD', 'Singapore Dollar (SGD)')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet')], default='cash', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
