# Generated by Django 5.2.15 on 2026-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingsgoal',
            options={'ordering': ['deadline'], 'verbose_name': 'Savings Goal', 'verbose_name_plural': 'Savings Goals'},
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
