# Generated by Django 5.2.15 on 2026-08-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_savingsgoal_options_savingsgoal_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
