# Generated by Django 5.2.15 on 2026-08-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_profile_bio_profile_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('German', 'German'), ('Hindi', 'Hindi')], default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('AED', 'UAE Dirham (AED)'), ('JPY', 'Japanese Yen (¥)')], default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='report_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='savings_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light Mode'), ('dark', 'Dark Mode'), ('system', 'System Default')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('AED', 'UAE Dirham (AED)'), ('JPY', 'Japanese Yen (¥)')], default='INR', max_length=10),
        ),
    ]
